# Generated by Django 5.2 on 2025-07-15 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BureauEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Depute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(max_length=10)),
                ('circonscription', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('partie_politique', models.CharField(max_length=100)),
                ('poste_partie', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('groupe_parlementaire', models.CharField(max_length=100)),
                ('statut', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Loi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('exposer', models.TextField()),
                ('piece', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('study_bureau_analysis', models.JSONField(blank=True, null=True)),
                ('conference_decision', models.JSONField(blank=True, null=True)),
                ('final_result', models.JSONField(blank=True, null=True)),
                ('etat', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('id_depute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lois', to='app.depute')),
            ],
        ),
        migrations.CreateModel(
            name='ConferencePresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('id_loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences_president', to='app.loi')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceLois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conference', models.DateTimeField()),
                ('id_conference_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_lois', to='app.conferencepresident')),
                ('id_loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loi')),
            ],
        ),
        migrations.CreateModel(
            name='AvisBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.CharField(max_length=50)),
                ('justification', models.TextField()),
                ('date', models.DateTimeField()),
                ('id_loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_bureau', to='app.loi')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('conference', 'Conférence'), ('pleniere', 'Plénière'), ('bill_update', 'Mise à jour de loi'), ('bureau_etudes', "Bureau d'études")], max_length=50, null=True)),
                ('id_depute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.depute')),
                ('id_loi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='app.loi')),
            ],
        ),
        migrations.CreateModel(
            name='Pleniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('id_conference_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plenieres', to='app.conferencepresident')),
                ('id_loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plenieres', to='app.loi')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oui', models.IntegerField(default=0)),
                ('nombre_non', models.IntegerField(default=0)),
                ('abstention', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.loi')),
                ('id_pleniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.pleniere')),
            ],
        ),
    ]
