# Generated by Django 5.2 on 2025-07-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loi',
            name='conference_decision',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loi',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loi',
            name='final_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loi',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loi',
            name='study_bureau_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('conference', 'Conférence'), ('pleniere', 'Plénière'), ('bill_update', 'Mise à jour de loi'), ('bureau_etudes', "Bureau d'études")], max_length=50, null=True),
        ),
    ]
